# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 053ab990248a09714d850180e847d9cc995e8b7448414ea051158589a6efbf828a78e3358da3235523d0ce9b2fe73b87a81f1a35660fde07ed3e8f036d6cc62d

test:
  secret_key_base: b40f2f715f0583ada6c2852893b6b3721cc7418064a5b523a2488ba85760ecb77c75b6a6c6c4cddee1c9aa9d0cd0d811b84d5bf2e9ce25922e7a92ff84cdb892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
